# Background
background_opacity 0.90

# mouse
open_url_with helium-browser
copy_on_select yes

# fonts
font_family      JetBrainsMono Nerd Font
italic_font      auto
bold_italic_font auto
font_size 12
disable_ligatures always

# window settings
remember_window_size no
window_padding_width 10
confirm_os_window_close 0
enable_audio_bell no
visual_bell_duration 0.0
